name: Zip js to bucket x.y.z/src.zip from tag 'lambda-x.y.z'

on:
  push:
    tags:
      - lambda-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get build version from tag
      id: release
      run: echo ::set-output name=tag::${GITHUB_REF:17}
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: eu-north-1
    # - name: Zip archive
    #   run: >-
    #     # zip
    # - name: Upload archive to lambda-src-bucket
    #   run: >-
    #     # aws
