name: Deploy version to production

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        uses: allenevans/set-env@v1.1.0
        with:
          env: "prod"
          aws_url: "hello-cloud-prod"

      - name: Build index for production
        run: >-
          GIT_SHA=${{github.sha}} NODE_ENV=${env} node src-index/main.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Upload index.html to prod env
        run: >-
          aws s3 cp index.html s3://${aws_url}/index.html
          --cache-control no-store
